const userData = [
	{
		content: [
			{
				id:1,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:2,
				src:require('./images/3.png'),
				isSide:false,
				total:99
			},{
				id:3,
				src:require('./images/3.png'),
				isSide:false,
				total:99
			},{
				id:4,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:5,
				src:require('./images/3.png'),
				isSide:false,
				total:99
			},{
				id:6,
				src:require('./images/3.png'),
				isSide:false,
				total:99
			},{
				id:7,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:8,
				src:require('./images/3.png'),
				isSide:false,
				total:99
			},{
				id:9,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:10,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:11,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:12,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			}
		]
	}, 
	{
		content: [
			{
				id:13,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:14,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:15,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:16,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:17,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:18,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:19,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:20,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:21,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:22,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:23,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:24,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			}
		]
	}, 
	{
		content: [
			{
				id:25,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:26,
				src:require('./images/3.png'),
				isSide:false,
				total:99
			},{
				id:27,
				src:require('./images/3.png'),
				isSide:false,
				total:99
			},{
				id:28,
				src:require('./images/3.png'),
				isSide:false,
				total:99
			},{
				id:29,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:30,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:31,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:32,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:33,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:34,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:35,
				src:require('./images/3.png'),
				isSide:true,
				total:99
			},{
				id:"",
				src:'',
				isSide:true,
				total:99
			}
		]
	},
]


export { userData }